dist: xenial
language: cpp
compiler: clang

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - boost1.67

script:
- cmake .
- cmake --build .
- ctest -VV --output-on-failure
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T bayan-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ulonforton:$BINTRAY_API_KEY "https://api.bintray.com/content/lonforton/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/bayan-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
